### ISSUE TITLE
crash with TypeError when requiring library

### ISSUE THREAD

**Issue by dradetsky** [kensho/check-more-types#30]
`npm i check-more-types` gives me 1.6.1. I create a file z.js containing

```
dmr@lapy:~/whale/node/web-hooks$ cat z.js 
var check = require('check-more-types');

dmr@lapy:~/whale/node/web-hooks$ node z.js 

/home/dmr/whale/node/web-hooks/node_modules/check-more-types/check-more-types.js:397
      check.verify.fn(fn, 'expected predicate function');
                   ^
TypeError: Cannot call method 'fn' of undefined
    at Object.mixin (/home/dmr/whale/node/web-hooks/node_modules/check-more-types/check-more-types.js:397:20)
    at module.exports (/home/dmr/whale/node/web-hooks/node_modules/check-more-types/check-more-types.js:537:11)
    at Array.forEach (native)
    at checkMoreTypes (/home/dmr/whale/node/web-hooks/node_modules/check-more-types/check-more-types.js:536:27)
    at Object.<anonymous> (/home/dmr/whale/node/web-hooks/node_modules/check-more-types/check-more-types.js:543:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by dradetsky** [comment]
dmr@lapy:~$ node --version
v0.10.36

**Comment by bahmutov** [comment]
Thanks for submitting a bug, quick question - what is the check-types version? We only support up to check-types@1.4.0 (check-types really breaks it API across major versions)

**Comment by dradetsky** [comment]
dmr@lapy:~/whale/node/web-hooks$ npm ls check-types
@ /home/dmr/whale/node/web-hooks
└── check-types@3.2.0 

did you forget to have check-more-types enforce the version?

**Comment by bahmutov** [comment]
yeah, this is it I believe. I should really add check-types@1.4.0 to the dependency list. Try this version and let me know what happens

**Comment by dradetsky** [comment]
you didn't put it on npm, and using the repo version is giving me annoying errors, which mean I can't afford to spend any more time on it:

dmr@lapy:~/code/js/node/git/check-more-types$ npm i
npm WARN deprecated node-beautify@0.0.2: please use js-beautify instead
npm WARN deprecated github-flavored-markdown@1.0.1: This project is long out of date. Use 'marked' instead.
npm ERR! Error: EACCES, mkdir '/home/dmr/.npm/osenv/0.0.3'
npm ERR!  { [Error: EACCES, mkdir '/home/dmr/.npm/osenv/0.0.3']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/dmr/.npm/osenv/0.0.3',
npm ERR!   parent: 'configstore' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

**Comment by dradetsky** [comment]
checked it. new version no longer throws error.
